AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./function
      Description: Build AWS Observability layer
      MemorySize: 512
      Timeout: 15
      Environment:
        Variables:
          ORIG_HANDLER: lambda_function.lambda_handler
          INPROCESS_EXPORTER: false
          AWS_LAMBDA_EXEC_WRAPPER: /opt/python/bin/opentelemetry-instrument
          PYTHONPATH: /opt/python:/var/runtime:/var/task
          OTEL_PYTHON_TRACER_PROVIDER: sdk_tracer_provider
      Policies:
        - AdministratorAccess
      Tracing: Active
      Layers:
        - !Ref AwsObservabilitySdk
        # - arn:aws:lambda:us-west-2:886273918189:layer:aws-observability-collector-beta:21
        - !Ref AwsObservabilityCollector
  AwsObservabilitySdk:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-observability-sdk-python38-beta
      Description: Lambda AWS Observability Python3.8 layer.
      ContentUri: ./aws_observability_sdk
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: makefile
  AwsObservabilityCollector:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-observability-collector-beta
      Description: Lambda AWS Observability Collector layer.
      ContentUri: ./aws_observability_collector
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: makefile
Metadata:
  AWS::ServerlessRepo::Application:
    Name: my-sar-test
    Description: >
      hehe haha,
    Author: Lei Wang
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: LICENSE
    Labels: ['layer', 'test', 'lambda', 'aot']
    HomePageUrl: https://github.com/wangzlei/awslambda-otel-sample/tree/master/sample-apps/Python-lambda-sam
    SemanticVersion: 0.1.0
    SourceCodeUrl: https://github.com/wangzlei/awslambda-otel-sample/tree/master/sample-apps/Python-lambda-sam