# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python: [3.8]
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: |
          echo tox...
          cd sample-apps/python-lambda-sam2
          tox
  # This workflow contains a single job called "build"
  build:
    needs: unit
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

#     env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_REGION: ${{matrix.region}}
    
    strategy:
      matrix:
        region: [us-west-1]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{matrix.region}}

      - name: sam build
        run: |
          echo $AWS_REGION
          cd sample-apps/python-lambda-sam2
          chmod +x run.sh
          ./run.sh -b
      
      - name: sam deploy
        if: ${{ success() }}
        run: |
          cd sample-apps/python-lambda-sam2
          ./run.sh -d
          
      - name: invoke Lambda
        if: ${{ success() }}
        run: |
          cd sample-apps/python-lambda-sam2
          ./run.sh -i
